name: Your New Jekyll Site
markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
encoding: utf-8
exclude:
  - README.md


custom:
    category:
        default: Default Category
        another: Another Category
    categories:
      - name:  default
        title: Default Category

      - name:  another
        title: Another Category

    scrollingLoadCount: 2

meta:
    author:
        name: Your Name
        email: your-email@example.com
        disqus: your-disqus-short-name
        gcse: 000346898720731947188:13h55x32l0y
        github: oriyao
        gravatar: 1cd8c12591616d8c22aaa624f8c07834
