name: Your New Jekyll Site
markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
encoding: utf-8
exclude:
  - README.md


custom:
    category:
        default: Default Category
        another: Another Category
    categories:
      - name:  default
        title: Default Category

      - name:  another
        title: Another Category

      - name:  another
        title: Another Category

    scrollingLoadCount: 0

meta:
    author:
        name: oriyao
        email: ylzhangyao@gmail.com
        disqus: your-disqus-short-name
        github: oriyao

