name: ORIYAO
markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
encoding: utf-8
exclude:
  - README.md


custom:
    category:
        book: BOOK 读书
        c: C 语言
        film: FILM 影视
        mooc: MOOC 公开课
        nba: NBA 篮球
        website: Website 网站相关
        
    categories:
      - name:  book
        title: 读书

      - name: c
        title: C 语言
        
      - name: film
        title: 影视
        
      - name: mooc
        title: MOOC

      - name: nba
        title: NBA
        
      - name:  website
        title: WebSite

    scrollingLoadCount: 0

meta:
    author:
        name: oriyao
        email: ylzhangyao@gmail.com
        github: oriyao

