name: ORIYAO
markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
encoding: utf-8
exclude:
  - README.md


custom:
    category:
        website: Website
        another: Another Category
        nba: NBA
    categories:
      - name:  website
        title: WebSite

      - name:  another
        title: Another Category

      - name:  nba
        title: NBA

    scrollingLoadCount: 0

meta:
    author:
        name: oriyao
        email: ylzhangyao@gmail.com
        github: oriyao

