name: ORIYAO
markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
encoding: utf-8
exclude:
  - README.md


custom:
    category:
        a: a~z
        b: BOOK 读书
        c: C 语言
        d: D
        e: E
        f: FILM 影视
        g: Geek
        h: HW 华为
        i: I
        j: J
        k: K
        l: Lifestyle
        m: MOOC 公开课
        n: NBA 篮球
        o: O
        p: Physics
        q: Q
        r: Remarks
        s: S
        t: T
        u: U
        v: V
        w: Website 网站相关
        x: X
        y: Y
        z: Z
        
    categories:
      - name:  b
        title: BOOK 读书

      - name: c
        title: C 语言
        
      - name: f
        title: FILM 影视
        
      - name: g
        title: Geek
     
      - name: h
        title: HW 华为
        
      - name: l
        title: Lifestyle
        
      - name: m
        title: MOOC

      - name: n
        title: NBA
        
      - name: p
        title: Physics
      
      - name: r
        title: remarks
        
      - name:  w
        title: WebSite

    scrollingLoadCount: 0

meta:
    author:
        name: oriyao
        email: ylzhangyao@gmail.com
        github: oriyao

