name: ORIYAO
markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
encoding: utf-8
exclude:
  - README.md


custom:
    category:
        a: a~z 索引
        b: BOOK 读书
        c: CODE 编程
        d: Digital 数码
        e: English 英语
        f: FILM 影视
        g: Geek 极客
        h: HW 华为
        i: I
        j: J
        k: K
        l: Lifestyle
        m: MOOC 公开课
        n: NBA 篮球
        o: O
        p: Physics 物理
        q: Q
        r: Remarks 搜集
        s: Software 软件
        t: T
        u: U
        v: V
        w: Website 网站相关
        x: X
        y: Y
        z: ZOOM 变焦
        
    categories:
      - name:  a
        title: A
        
      - name:  b
        title: BOOK 读书

      - name: c
        title: C 语言

      - name: d
        title: Digital 数码
        
      - name: e
        title: E

      - name: f
        title: FILM 影视
        
      - name: g
        title: Geek
        
      - name: h
        title: HW 华为
        
      - name: i
        title: I
        
      - name: j
        title: J

      - name: k
        title: K
        
      - name: l
        title: Lifestyle
        
      - name: m
        title: MOOC

      - name: n
        title: NBA
        
      - name: o
        title: O
        
      - name: p
        title: Physics
        
      - name: q
        title: Q
      
      - name: r
        title: remarks
        
      - name: s
        title: S
        
      - name: t
        title: T
        
      - name: u
        title: U
        
      - name: v
        title: V
        
      - name:  w
        title: WebSite
        
      - name: x
        title: X
        
      - name: y
        title: Yao
        
      - name: z
        title: 变焦

    scrollingLoadCount: 0

meta:
    author:
        name: oriyao
        email: ylzhangyao@gmail.com
        github: oriyao

